replicaCount: 2

image:
  repository: registry.gitlab.com/tanphat.it270396/hello-app
  tag: b0258a0a
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

config:
  APP_VERSION: "v2.0-helm"
  LOG_LEVEL: "INFO"
  GREETING: "Hello"
  DB_HOST: "postgres.default.svc.cluster.local"
  STARTUP_TIME: "0"

secrets:
  API_KEY: "demo-api-key-do-not-commit-real-secret"
  DB_PASSWORD: "demo-password-123"
  
probes:
  liveness:
    path: /healthz
    initialDelaySeconds: 10
    periodSeconds: 10
    failureThreshold: 3
  readiness:
    path: /ready
    initialDelaySeconds: 2
    periodSeconds: 5
    failureThreshold: 3
  startup:
    path: /ready
    periodSeconds: 5
    failureThreshold: 30

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi
