replicaCount: 5

config:
  APP_VERSION: "v2.0-prod"
  LOG_LEVEL: "WARN"
  GREETING: "Production"
  DB_HOST: "postgres.prod.svc.cluster.local"

secrets:
  API_KEY: "prod-api-key-replace-with-real"
  DB_PASSWORD: "prod-password-replace-with-real"
